config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :cart, only: %i[show destroy]

  resources :line_items, only: %i[create destroy]
  resources :orders, except: %i[edit update]
  resources :products, only: %i[index show] do
    collection do
      post :index
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at current_sign_in_at email id sign_in_count updated_at]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  include AASM

  belongs_to :user

  has_one :order, dependent: :destroy

  has_many :line_items, dependent: :destroy

  aasm do
    state :opened, initial: true
    state :closed

    event :close do
      transitions from: :opened, to: :closed
    end
  end

  def line_items_amount
    line_items.sum(:amount)
  end

  def subtotal
    line_items.sum { |line_item| line_item.product.price * line_item.amount }
  end

  def empty?
    line_items.empty?
  end
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :amount, presence: true, numericality: { greater_than: 0 }

  default_scope { order(:created_at) }
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :cart

  validates :total, presence: true
  validates :total, numericality: { greater_than: 0 }
  validates :shipping_total, numericality: { greater_than_or_equal_to: 0 }

  after_create_commit :close_cart

  private

  def close_cart
    cart.close!
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord

  include Rails.application.routes.url_helpers

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  has_one_attached :image

  has_many :line_items, dependent: :destroy

  acts_as_taggable_on :categories

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at name]
  end

  def image_url
    image.attached? ? url_for(image) : '/assets/noimage.jpg'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :carts, dependent: :destroy
  has_many :orders, through: :carts
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_cart

  private

  def current_cart
    @current_cart ||= current_user.carts.opened.first_or_create
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < TatanStoreController
  def show; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @products = Product.all.sample(8)
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < TatanStoreController
  def create
    if LineItemCreator.call(current_cart, line_item_params)
      redirect_back fallback_location: root_path, notice: "<strong>#{product.name}</strong> was added to cart"
    else
      redirect_back fallback_location: root_path, alert: "<strong>#{product.name}</strong> can not be added to cart"
    end
  end

  def destroy
    if line_item.destroy
      destroy_success!
    else
      redirect_to cart_path, alert: "<strong>#{line_item.product.name}</strong> can not be removed from cart"
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:product_id, :amount)
  end

  def line_item
    @line_item ||= current_cart.line_items.find(params[:id])
  end

  def product
    @product ||= Product.find(line_item_params[:product_id])
  end

  def destroy_success!
    flash[:notice] = "<strong>#{line_item.product.name}</strong> was removed from cart"
    if current_cart.line_items.any?
      redirect_back fallback_location: cart_path
    else
      redirect_to cart_path
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < TatanStoreController
  before_action -> { redirect_to cart_path }, only: %i[new create], if: -> { current_cart.empty? }
  after_action :load_current_cart!, only: :create

  def index
    @orders = orders.page(params[:page])
  end

  def show
    order
  end

  def new
    shipping_total = 9.99
    @order = current_cart.build_order(total: current_cart.subtotal + shipping_total,
                                      shipping_total:)
  end

  def create
    @order = current_cart.build_order(order_params)
    if @order.save
      @current_cart = nil
      redirect_to root_path, notice: I18n.t('messages.orders.create.success')
    else
      flash[:alert] = I18n.t('messages.orders.create.failed')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if order.destroy
      flash[:notice] = I18n.t('messages.orders.destroy.success')
    else
      flash[:alert] = I18n.t('messages.orders.destroy.failed')
    end
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:total, :shipping_total)
  end

  def orders
    @orders ||= current_user.orders.order('created_at DESC')
  end

  def order
    @order ||= orders.find(params[:id])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < TatanStoreController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @products = params[:category].present? ? Product.tagged_with(params[:category]) : Product.all
    @products = @products.page(params[:page]).per 12

    if params[:page]
      render turbo_stream: turbo_stream.append("products", partial: "products/scrollable_list")
    end
  end

  def show
    @product = Product.find(params[:id])
    @related_products = @product.find_related_categories.limit(8)
  end
end

app/controllers/tatan_store_controller.rb
# frozen_string_literal: true

class TatanStoreController < ApplicationController
  before_action :authenticate_user!
  before_action :load_current_cart!, if: :current_user

  private

  def load_current_cart!
    current_cart
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def cart_line_items_amount
    current_cart.line_items_amount
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

module LineItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/carts/show.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <h3>Cart</h3>
    <hr>
    <% if current_cart.line_items.any? %>
      <table class="table">
        <%= render partial: 'line_items/table_body', locals: { cart: current_cart } %>
        <tfoot>
          <td></td>
          <td></td>
          <td>Total (<%= pluralize(current_cart.line_items_amount, 'item') %>):</td>
          <th class="text-end"><%= number_to_currency(current_cart.subtotal)%></th>
        </tfoot>
      </table>

      <div class="d-flex flex-row-reverse align-items-center justify-content-between">
        <%= link_to 'Checkout', new_order_path, class: 'btn btn-success mt-auto' %>
      </div>
    <% else %>
      <p>No items to show</p>
    <% end %>
  </div>
</section>

app/views/home/index.html.erb
<div class="banner mt-5">
  <img src="/assets/banner.jpg" alt="">
</div>

<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <%= render @products %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TatanStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- <meta name="turbo-visit-control" content="reload"> -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="/assets/scripts.js"></script>
  </head>

  <body>
    <%= render partial: 'layouts/shared/header' %>
    <%= render partial: 'layouts/shared/flash_messages' %>
    <%= yield %>
    <%= render partial: 'layouts/shared/footer' %>
    <!-- <script type="text/javascript">
      var fadeTarget = document.getElementById("flash-message")

      if(fadeTarget) {
        setTimeout(function(){
          var fadeEffect = setInterval(function () {
            if (!fadeTarget.style.opacity) fadeTarget.style.opacity = 1;

            if (fadeTarget.style.opacity > 0) {
              fadeTarget.style.opacity -= 0.1;
            } else {
              clearInterval(fadeEffect);
              fadeTarget.remove();
            }
          }, 200);
        }, 1500)
      }
    </script> -->
  </body>
</html>

app/views/layouts/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert" id='flash-message'>
    <%= msg.html_safe %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer class="py-3 bg-dark fixed-bottom">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Tatan 2024</p>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="/">Tatan Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= render partial: 'layouts/shared/left_menu' %>
      <%= render partial: 'layouts/shared/right_menu' %>
    </div>
  </div>
</nav>

app/views/layouts/shared/_left_menu.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
  <li class="nav-item">

  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle <%= 'active' if controller_name == 'products' %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Products
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to 'All Products', products_path, class: "dropdown-item" %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= link_to 'Men', products_path(category: 'Men'), class: "dropdown-item" %>
      </li>
      <li>
        <%= link_to 'Women', products_path(category: 'Women'), class: "dropdown-item" %>
      </li>
    </ul>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Orders', orders_path, class: "nav-link #{'active' if controller_name == 'orders'}" %>
    </li>
  <% end %>
</ul>

app/views/layouts/shared/_right_menu.html.erb
<ul class="navbar-nav d-flex">
  <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.email%>
      </a>
      <ul class="dropdown-menu dropdown-menu-end">
        <li><%= link_to 'Account Setting', edit_user_registration_path, class: 'dropdown-item' %></li>
        <li><hr class="dropdown-divider"></li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, data: { 'turbo-method': :delete }, class: 'dropdown-item' %>
        </li>
      </ul>
    </li>
    <li class="nav-item">
      <%= link_to cart_path, class: 'btn btn-info' do %>
        <i class="bi-cart-fill me-1"></i>
        <span>Cart</span>
        <span class="badge bg-dark text-white ms-1 rounded-pill">
          <%= cart_line_items_amount %>
        </span>
      <% end %>
    </li>
  <% else %>
    <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
  <% end %>
</ul>

app/views/line_items/_line_item.html.erb
<tr>
  <td>
    <img class="" src="<%= line_item.product.image_url %>" height='80' alt="..." />
  </td>
  <td>
    <div><%= line_item.product.name %></div>
    <% if line_item.cart.opened? %>
      <%= link_to 'Delete', line_item_path(line_item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-danger text-decoration-none' %>
    <% end %>

  </td>
  <td><%= line_item.amount %></td>
  <td class="text-end"><%= number_to_currency(line_item.product.price) %></td>
</tr>

app/views/line_items/_table_body.html.erb
<tbody>
  <%= render cart.line_items %>
</tbody>

app/views/orders/_order.html.erb
<tr>
  <td><%= order.created_at.to_i %></td>
  <td><%= local_time_ago(order.created_at) %></td>
  <td class="text-end"><%= number_to_currency(order.total) %></td>
  <td>
    <div class="row">
      <div class="col-6 text-center">
        <%= link_to 'View order details ', order_path(order), class: 'text-decoration-none' %>
      </div>
      <div class="col-6">
        <%= link_to 'Delete', order_path(order), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-decoration-none' %>
      </div>
    </div>
  </td>
</tr>

app/views/orders/index.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <h3>Your Orders</h3>
    <hr>

    <% if @orders.any? %>
      <table class="table">
        <thead>
          <th>Order Number</th>
          <th>Date</th>
          <th>Total</th>
          <th></th>
        </thead>
        <tbody>
          <%= render @orders %>
        </tbody>
      </table>

      <%= paginate @orders %>

    <% else %>
      <p>No orders to show</p>
    <% end %>
  </div>
</section>

app/views/orders/new.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-9 mb-4">
        <ul class="list-group">
          <li class="list-group-item">
            <h5>Items</h5>
            <table class="table">
              <%= render partial: 'line_items/table_body', locals: { cart: @order.cart } %>
            </table>
          </li>
        </ul>

      </div>

      <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-3">
        <ul class="list-group">
          <li class="list-group-item">
            <h5>Order Summary</h5>
            <table class="table">
              <tbody>
                <tr>
                  <td>Subtotal(<%= pluralize(@order.cart.line_items_amount, 'Item') %>)</td>
                  <td class="text-end">
                    <%= number_to_currency(@order.cart.subtotal) %>
                  </td>
                </tr>
                <tr>
                  <td>Shipping</td>
                  <td class="text-end">
                    <%= number_to_currency(@order.shipping_total) %>
                  </td>
                </tr>

              </tbody>
              <tfoot>
                <tr>
                  <th>Total:</th>
                  <th class="text-end">
                    <%= number_to_currency(@order.total) %>
                  </th>
                </tr>
              </tfoot>
            </table>
          </li>
          <li class="list-group-item text-center">
            <%= form_with model: @order do |f| %>
              <%= f.hidden_field :shipping_total %>
              <%= f.hidden_field :total %>
              <%= f.submit 'Create Order', class: 'btn btn-success mt-auto' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <h3>Order Details</h3>
    <div class="row">
      <div class="col-12 col-sm-7 col-md-6">
        Ordered on <%= local_time_ago(@order.created_at) %>
      </div>
      <div class="col-12 col-sm-5 col-md-6">
        Order #<%= @order.created_at.to_i %>
      </div>
    </div>
    <hr>
    <table class="table">
      <%= render partial: 'line_items/table_body', locals: { cart: @order.cart } %>
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td>Subtotal (<%= pluralize(@order.cart.line_items_amount, 'item') %>):</td>
          <td class="text-end"><%= number_to_currency(@order.cart.subtotal)%></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>Shipping:</td>
          <td class="text-end"><%= number_to_currency(@order.shipping_total)%></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>Total:</td>
          <th class="text-end"><%= number_to_currency(@order.total)%></th>
        </tr>
      </tfoot>
    </table>
  </div>
</section>

app/views/products/_next_page.html.erb
<%= turbo_frame_tag(
      "products-page-#{@products.next_page}",
      # autoscroll: true,
      loading: :lazy,
      src: path_to_next_page(@products, format: :turbo_stream),
      target: "_top",
      class: 'products-turbo-frame'
    ) do %>

<% end %>

app/views/products/_product.html.erb
<div class="col mb-5">
  <div class="card h-100">
    <!-- Product image-->
    <img class="card-img-top" src="<%= product.image_url %>" height='198' alt="..." />
    <!-- Product details-->
    <div class="card-body">
      <%= link_to product_path(product), class: 'text-decoration-none' do %>
        <div class="text-center">
          <!-- Product name-->
          <h5 class="fw-bolder"><%= product.name %></h5>
        </div>
      <% end %>

    </div>
    <!-- Product actions-->
    <div class="card-footer pt-0 border-top-0 bg-transparent">
      <div class="text-center mb-2">
        <!-- Product price-->
        <span class="price"><%= number_to_currency(product.price) %></span>
      </div>
      <div class="text-center">
        <%= button_to 'Add to cart', line_items_path, method: :post, params: { line_item: { product_id: product.id, amount: 1 } }, class: 'btn btn-primary mt-auto' %>
      </div>
    </div>
  </div>
</div>

app/views/products/_scrollable_list.html.erb
<%= render @products %>
<%= render partial: "next_page" unless @products.last_page? %>

<script type="text/javascript">
  var el = document.getElementById('products-page-<%= @products.current_page %>');
  el.classList.add('d-none');
</script>

app/views/products/index.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center" id="products">

      <%= render @products %>
      <%= render partial: 'next_page' %>
    </div>

  </div>
</section>

app/views/products/show.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <%= link_to 'Products', products_path, class: 'text-decoration-none' %>
        </li>
        <% @product.category_list.each do |category| %>
          <li class="breadcrumb-item">
            <%= link_to category, products_path(category:), class: 'text-decoration-none' %>
          </li>
        <% end %>
        <li class="breadcrumb-item active" aria-current="page">
          <%= @product.name %>
        </li>
      </ol>
    </nav>

    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="<%= @product.image_url %>" alt="..." /></div>
      <div class="col-md-6">
        <h1 class="display-5 fw-bolder"><%= @product.name %></h1>
        <div class="fs-5 mb-5">
          <span><%= number_to_currency(@product.price) %></span>
        </div>

        <div class="d-flex">
          <%= form_with model: LineItem.new, url: line_items_path do |f|%>
            <%= f.hidden_field :product_id, value: @product.id %>
            <div class="row">
              <div class="col-5">
                <div class="input-group mb-3">
                  <button class="btn btn-primary border-light-subtle btn-subtract" type="button" id="button-addon1">-</button>
                  <%= f.number_field :amount, class: 'form-control text-center item-quantity', value: 1, min: 1 %>
                  <button class="btn btn-primary border-light-subtle btn-add" type="button" id="button-addon2">+</button>
                </div>
              </div>
              <div class="col">
                <%= f.button class: 'btn btn-primary flex-shrink-0', type: 'submit' do %>
                  <i class="bi-cart-fill me-1"></i>
                  Add to cart
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <h2 class="fw-bolder mb-4">Related products</h2>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <%= render @related_products %>
    </div>
  </div>
</section>